# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release-project:
    name: Release different versions of Text file
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Download content
        uses: actions/download-artifact@v2
        with:
          name: P008165/P008165.opf/base
      - name: Archive base content
        uses: thedoctor)/zip-release@master
        with:
          filename: base.zip
      - name: Create Github Release
        id: 
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          - name: upload Release assets
            uses: actions/upload-release-asset@v1
            env:
              GITHUB_TOKEN: ${{  secrets.GITHUB_TOKEN }}
            with: 
              upload_url: ${{ steps.create-new-release.outputs.upload_url }}
              asset_path: ./base.zip
              asset_name: site-v${{ github.run_number }}.zip
              asset_content_type: text/zip
  build-project:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
