name: CI
on:
  push:
    paths:
    branches: [ main ]
  workflow_dispatch:
jobs:
  add-description:
    name: Adding 
    runs-on: ubuntu-latest
    steps:
      - name: Adding the description
        run: |
          curl  -H "Authorization: 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" \
                --request PATCH https://api.github.com/repos/ta4tsering/P008165
                --data '{"name":"P008165", "description":"tashi delek"}'
                
        shell: bash                




