name: CI
on:
  push:
    paths:
    "P008165/.github/*"
    # branches: [ main ]
jobs:
  Add-discription:
      name: Release different versions of Text file
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

          shell: python
        - name: Repo Sync
          uses: kbrashears5/github-action-repo-sync@master
          with:
            TYPE: npm
            PATH: ./metadata.json
            TOKEN: ${{ secrets.ACTIONS }}