name: Create Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  add-description:
    name: Running Environment
    runs-on: ubuntu-latest
    steps:
      - name: adding description
        env: 
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl  -H "Authorization: bearer ${GITHUB_TOKEN}" \
                -X PATCH https://api.github.com/repos/ta4tsering/P008165 \
                -d '{"name":"P008165", "description":"tashi"}'


