name: CI
on:
  push:
    paths:
    branches: [ main ]
  workflow_dispatch:
jobs:
  add-description:
    name: Adding 
    runs-on: ubuntu-latest
    steps:
      - name: Adding the description
        env:
          GITHUB_TOKEN: ${{  secrets.GITHUB_TOKEN }}
        run: |
          curl  -X PATCH \
                -u $GITHUB_TOKEN:x-oauth-basic \
                https://api.github.com/repos/ta4tsering/P008165 \
                -d '{"name":"P008165", "description":"tashi delek"}'
                              




